# Generated by Django 5.0.8 on 2025-02-21 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('rounds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='round_winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='players.player'),
        ),
    ]
